name: Build test
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build
      run: ./build-llvm.py --lto full --no-update --build-stage1-only --shallow-clone --target AArch64;X86;ARM --branch main

    - uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r clang.zip install

    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: |
          clang.zip
